### PR TITLE
Fixed exception of link_types fields, when you try to choose one of t…

### PR DESCRIPTION
**Pull request by Piterden**
# …he types @

### CODE REVIEW

**Comment by RyanThompson** [comment]
What's wrong with this the way it was? It's been like this forever and working OK.

**Comment by Piterden** [comment]
When I tried to add navigation element, there was an exception. Php undefined index "link_type" in $_GET array. And later I have the same exception in page module

**Comment by Piterden** [comment]
Sorry, not the same exception in page module, there is "Call to a member function getEntryModelName() on null"
image

**Comment by Piterden** [comment]
About $_GET:
I suppose this is not the best way to use $_GET array and URL parameters with Laravel in 2016
Why you don't using laravel routing to translate parameters to the request?

**Comment by RyanThompson** [comment]
I see.. can you share an image of the exception from the navigation module as well? So I can see your URL / query there too.

Do you have an entry in your `{ref}_pages_types` table with the ID of 1 that is not also deleted?

**Comment by RyanThompson** [comment]
And for navigation - can you `dd($_GET)` here: https://github.com/anomalylabs/navigation-module/blob/master/src/Http/Controller/Admin/LinksController.php#L84

And let me know what it says.

**Comment by RyanThompson** [comment]
I can change $_GET to `$this->request->get('foo');` too but there shouldn't be a problem either way. The reason it's in the query and not in the route is because arguments are/were variable.

**Comment by Piterden** [comment]
I don't understand reason
Why you don't use `admin/navigation/links/{menu}/create/{link_type}`?
I have 2 variables in route

If you use laravel - your route on each page load rewriting by server to 

```
/index.php?q=admin/navigation/links/top_menu/create/page_link_type
```

If you have parameters in URL, your server receives

```
/index.php?q=admin/navigation/links/top_menu/create/page_link_type?param=value&param2=value2
```

You should use `&` but not `?` if you want to see this params in controller

**Comment by Piterden** [comment]
And what do you don't like in standart Laravel's system to pass vars to request?

**Comment by RyanThompson** [comment]
So in the controller if you replace the variable with `$this->request->get('link_type')` then it works correctly?

One reason I don't route them as petty as it seems is because I don't do it that way everywhere else I use this pattern. I don't like things being 1 way here and a different way there. So I would need to update all instances of this everywhere. 

That said.. I usually use the request object so it's weird the $_GET is here at all. If you can confirm the request object Ill get it patched and make sure it's consistent across the board. There are a lot of areas that use this kind of workflow but like I said - they're usually using the request object.

Thanks!

**Comment by RyanThompson** [comment]
It's not that I don't like it - I love URL parameters. But they start introducing hard dependencies on values which is not always the case (as was the case here when I started doing things like this in Pyro). So for optional / variable number of arguments I pass them in via query string. However things like IDs are hard dependencies and the route reflects that.

**Comment by RyanThompson** [comment]
Can you update and confirm the fix for me please? https://github.com/anomalylabs/navigation-module/commit/b8bb530b0c2998899d157c97687e1beaf84aeb24#diff-7250f249236e9bc2a742825d5a4a3f01R84

I will keep an eye out on $_GET anywhere else too - I was unaware that server configuration with rewriting could have an effect like this though I think it's technically from misconfiguration? Rewriting should be re-mapping those for you right?

Either way - the commit referenced is much more proper ^_^

**Comment by Piterden** [comment]
here is my exception
image

**Comment by Piterden** [comment]
This is `dd($_GET);`
image

**Comment by Piterden** [comment]
`dd($this->request->get('link_type'));`
image

**Comment by RyanThompson** [comment]
Ok - looks like your server is not rewriting correctly. Let me go grab someone who's more versed in this stuff than myself.

**Comment by Piterden** [comment]
I dont have your params
image

**Comment by keevitaja** [comment]
Please give us your os, server and php type. This is not a rewriting issue...

**Comment by Piterden** [comment]
I use **nginx** and **php7.0-fpm**

**Comment by Piterden** [comment]
One moment

**Comment by RyanThompson** [comment]
@Piterden maybe run a quick test in some random test.php file and see if you get any parameters by dumping $_GET

Then try it again in the index.php just to make sure we know exactly what's going on.

**Comment by Piterden** [comment]
``` bash
~/web/dev.web812.pro/public_html$ uname -a
Linux dev.web812.pro 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

``` bash
~/web/dev.web812.pro/public_html$ nginx -v
nginx version: nginx/1.10.0 (Ubuntu)
```

``` bash
~/web/dev.web812.pro/public_html$ php -v
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by Piterden** [comment]
image

**Comment by Piterden** [comment]
You could try

**Comment by keevitaja** [comment]
i am pretty close to your server configuration

```
nginx version: nginx/1.10.1
PHP 7.0.11 (cli) (built: Sep 16 2016 18:52:44) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11, Copyright (c) 1999-2016, by Zend Technologies
Linux laptop 4.4.21-1-MANJARO #1 SMP PREEMPT Thu Sep 15 19:16:23 UTC 2016 x86_64 GNU/Linux
```

I am attaching my config files 

https://dl.dropboxusercontent.com/u/60672885/conf.zip

**Comment by RyanThompson** [comment]
@Piterden ok cool - now try the same test in your index.php file.

**Comment by Piterden** [comment]
Works in index.php
image

**Comment by RyanThompson** [comment]
And lastly with a path like example?test=test and with/without slash too for good measure. Somethings screwy!

**Comment by Piterden** [comment]
One moment
Here is my server configs
[configs.tar.gz](https://github.com/anomalylabs/navigation-module/files/487878/configs.tar.gz)

**Comment by Piterden** [comment]
Without slash rewriting to slash

**Comment by joe642** [comment]
@Piterden have a look at this link http://stackoverflow.com/questions/14854050/laravel-with-nginx-parameters-are-empty

**Comment by Piterden** [comment]
Thanks guys

Problem was in the rewrite rule.

``` nginx
try_files $uri $uri/ /index.php;
```

Server behavior was exsactly like I explain ahead in this thread.

This is the right rule:

``` nginx
try_files $uri $uri/ /index.php?q=$uri&$args;
```

**Comment by RyanThompson** [comment]
@Piterden woo hoo! I think things should work as expected now ^_^

**Comment by Piterden** [comment]
Yea)
And other modules too.

What do you think about saving entries from admin interface with `ctrl/cmd + s` shortcut?
I can implement this functionality - it's not hard)

**Comment by RyanThompson** [comment]
@Piterden check out this issue: https://github.com/pyrocms/pyrocms/issues/3731

We need a keymap standard / framework for this so it's the same everywhere.

Need keys for form actions, section buttons, tables (table row / selection keys), and I think that's it..

For example Ctl + n for the create buttons. stuff like that. We'd store the bindings in the ButtonRegistry but just need to map out what we need.

If you wanna take this on - please start up another issue I know a few of us who are very interested!

**Pull request closed without merging**
